== edfisica-livro

Elaboração de um Livro de Educação Física para o Ensino Médio (1º - 3º ano)

=== Linguagem de escrita

O livro está sendo escrito utilizando a linguagem asciidoc:

http://powerman.name/doc/asciidoc

=== Como posso contribuir?

Ótimo! Você quer contribuir? Agora você tem duas opções,
escrever sobre um tema novo ou contribuindo para um tema existente.

==== Escrevendo um novo tema
Para escrever sobre um novo tema, basta criar um novo arquivo, dentro do
diretório livro e começar a escrever. Você pode utilizar este arquivo como 
base para começar a escrever sobre o seu tema.

NOTE: Embora o github possibilite editar e vizualizar arquivos .asciidoc,
é melhor utilizar arquivos .txt, pois o github modifica os arquivos excluindo
todas as quebras de linhas quando usamos .asciidoc. Portanto, *sempre crie 
arquivos .txt*.

==== Atualizando um tema existente
Para atualizar um tema existente, escolha um arquivo para editar em:
https://github.com/edusantana/edfisica-livro/tree/master/livro

==== Como funcionar o processo da contribuição?
Quando você faz qualquer alteração nos arquivos do projeto, o github faz um
'fork', basicamente ele cria uma cópia do projeto e disponibiliza ela somente
para você. Todas as alterações que você realiza estão disponíveis num 
repositório, criado automaticamente pelo github, onde você é o dono. 
Qualquer alteração que você realizar ficará disponível neste 'fork' pessoal.

NOTE: As alterações só estarão disponíveis após você submeter as alterações
para o projeto original. Você pode fazer isso através da opção 'Pull Request'.

=== Ferramentas

No windows usar o github for windows: http://github-windows.s3.amazonaws.com/GitHubSetup.exe

Editor de texto: http://www.sublimetext.com/

Plugin-in-assciidoc: https://github.com/SublimeText/AsciiDoc (ver instruções de instalação)

==== Gerando versão pdf

O seguinte comando gera edfisica-livro.pdf em ../pdf:

 ~/ambiente/asciidoc-8.6.8/a2x.py edfisica-livro.txt

WARNING: Certifique-se de que existe o diretório: _edfisica-livro/pdf_

